CREATE TABLE ROLES(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(60) NOT NULL,
  DESCRIPTION VARCHAR(180) NOT NULL,
  ENABLED CHAR(1) DEFAULT 'Y',
  CONSTRAINT PK_ROLES PRIMARY KEY(ID),
  CONSTRAINT CK_ROLE_ENABLED CHECK (ENABLED IN ('Y', 'N'))
);

CREATE TABLE USERS(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(32) NOT NULL,
  EMAIL VARCHAR(160) NOT NULL,
  ENABLED CHAR(1) DEFAULT 'Y',
  NAME VARCHAR(160) NOT NULL,
  PASSWORD VARCHAR(160) NOT NULL,
  ACCOUNT_NON_EXPIRED CHAR(1) DEFAULT 'Y',
  ACCOUNT_NON_LOCKED CHAR(1) DEFAULT 'Y',
  CREDENTIALS_NON_EXPIRED CHAR(1) DEFAULT 'Y',
  CONSTRAINT PK_USERS PRIMARY KEY(ID),
  CONSTRAINT CK_USER_ENABLED CHECK (ENABLED IN ('Y', 'N'))
);